version: '3.4'

services:
  mysql:
    image: icommerce:mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    command:
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=icommerce_no_data